### ISSUE TITLE
Cannot cancel student attendance in group lesson

### ISSUE THREAD

**Issue by kamilszczesny** [Zamenhof/api#1]
I tried to remove learners from test lessons moment ago

but I'm unable
I searched for learner and displayed his panel - which is empty
these are test lessons and test learners
<img width="882" alt="zrzut ekranu 2018-07-20 o 08 59 24" src="https://user-images.githubusercontent.com/1933153/42988006-60ec553c-8bfb-11e8-9b57-fa7658efca42.png">
<img width="1325" alt="zrzut ekranu 2018-07-20 o 08 59 58" src="https://user-images.githubusercontent.com/1933153/42988007-610890bc-8bfb-11e8-8b6f-3cf19a555a11.png">

for example I have test learner: 42736
who is assigned to lesson group: 182
but this is not visible in student Panel

**Comment by patzamgit** [comment]
Sorry, I'm a bit late for this one. I can see that the GroupID 182 is now empty: 
[https://www.screencast.com/t/jIL5P2J4tVOv](url)

And the student 42736 doesn't have scheduled lessons: 
[https://www.screencast.com/t/eYUWkdftiJ](url)
