### ISSUE TITLE
P8- New class email notification (part 1)

### ISSUE THREAD

**Issue by patzamgit** [Zamenhof/api#10]
The teacher should receive a single email per class instead of an email per student.

**Comment by mcconc** [comment]
Copying the proposed email text (needs sign off by Debra):


Subject: You have a new class from Excedo!

Text: Hi <teacher_first_name>,

You have a new class!

Group ID 256
School Excedo
Start Time (your time) Fri, August 10, 2018 19:30
Time before the lesson 2 day(s) 10 hour(s) 5 minute(s)
Course type General English
Course Open Course

Best regards,
Zamenhof.net
--
