### ISSUE TITLE
[Bug] Two classes with the same teacher in one time

### ISSUE THREAD

**Issue by kamilszczesny** [Zamenhof/api#23]
Somehow Zamenhof interface allowed scheduling 2 classes for one teacher in one time.
Later 2 learners booked these 2 classes and one tried attending class one, second attending class two.
Teacher joined just one of the classes.

   {
      "classid": "463214",
      "classdate": "2018-08-27 20:00:00",
      "duration": "25",
      "teacherid": "386",
      "groupid": "298",
      "livelessonid": "8963",
      "tname": "Yasmeen Coaxum",
      "resume": "Yasmeen is a certified CELTA ESL Teacher with an additional certificate in Teaching Business English.\n\nHer background is in the field of media: Magazine Publishing, Radio, TV Production & Consumer Marketing, but she made the transition to teaching and has been doing so for about 10 years. Her first teaching job was in Tokyo, Japan for 1.5 years, and she has also taught academic English in the capital of Turkey.\n\nShe currently works as a Corporate Language Trainer for companies in a variety of industries in Berlin, Germany, combining her previous corporate media experience with her love of teaching English.  \n\nYasmeen believes in continual growth in the field of ESL, and therefore frequently attends professional conferences and professional development workshops to enhance her teaching methods. She is also attending an MA program in Applied Linguistics and Language Acquisition at the University of Barcelona in September. \n\nShe believes that the top priority in language learning is to provide an atmosphere that makes students feel comfortable enough to use the language as much as possible.",
      "title": "Module 3: Communicate your value",
      "join_url": "https://zoom.us/j/921990399",
      "zoom_error": "",
      "students": "2",
      "timezone": "Asia/Tokyo"
    },
    {
      "classid": "463212",
      "classdate": "2018-08-27 20:00:00",
      "duration": "25",
      "teacherid": "386",
      "groupid": "298",
      "livelessonid": "8963",
      "tname": "Yasmeen Coaxum",
      "resume": "Yasmeen is a certified CELTA ESL Teacher with an additional certificate in Teaching Business English.\n\nHer background is in the field of media: Magazine Publishing, Radio, TV Production & Consumer Marketing, but she made the transition to teaching and has been doing so for about 10 years. Her first teaching job was in Tokyo, Japan for 1.5 years, and she has also taught academic English in the capital of Turkey.\n\nShe currently works as a Corporate Language Trainer for companies in a variety of industries in Berlin, Germany, combining her previous corporate media experience with her love of teaching English.  \n\nYasmeen believes in continual growth in the field of ESL, and therefore frequently attends professional conferences and professional development workshops to enhance her teaching methods. She is also attending an MA program in Applied Linguistics and Language Acquisition at the University of Barcelona in September. \n\nShe believes that the top priority in language learning is to provide an atmosphere that makes students feel comfortable enough to use the language as much as possible.",
      "title": "Module 3: Communicate your value",
      "join_url": "https://zoom.us/j/293331978",
      "zoom_error": "",
      "students": "2",
      "timezone": "Asia/Tokyo"
    },

Please investigate how this happened and how to make it impossible in the future.

**Comment by patzamgit** [comment]
This issue was related to the server latency. It will not happen with our new AWS cloud infrastructure.
