### ISSUE TITLE
Inconsistent search results in Attendance View

### ISSUE THREAD

**Issue by kamilszczesny** [Zamenhof/api#25]
When logging in as Advisor to Zamenhof on 2 different accounts.
And going to attendance view, searching for classes in given date (example of 20th of September) 2 users get different results.
I'm attaching screenshots taken in the same time on 2 different accounts.
![image 4](https://user-images.githubusercontent.com/1933153/45874038-277b4680-bd94-11e8-8c19-25f7dd1129d9.png)
![zrzut ekranu 2018-09-21 o 11 39 47](https://user-images.githubusercontent.com/1933153/45874058-3235db80-bd94-11e8-82bf-f49e88a2811b.png)

Please investigate what is the reason?

**Comment by indrajitlahiri** [comment]
What are the advisor accounts in these tests. Please provide the account credentials for both screen shots.

**Comment by indrajitlahiri** [comment]
Kamil account timezone is - Europe/Warsaw
Helena account timezone is - Asia/Tokyo
So for Kamil the lesson date is 20 Sep and for Helena the same is 21 Sep, the difference in the report is showing accordingly.

**Comment by patzamgit** [comment]
You will find more information about the time zone references on this page: 
https://github.com/Zamenhof/public/wiki/Time-Zone-References
