### ISSUE TITLE
P1 - Dates format in API methods

### ISSUE THREAD

**Issue by patzamgit** [Zamenhof/api#4]
There are multiple places in API methods we are using that we pass date/time parameters or receive date/time properties.

**Currently**:
Date/time values are presented in time zone taken from school setting in Zamenhof - this is Tokyo/Japan timezone.
We will present class dates in the future to students in multiple timezones and want to limit transferring date/time values between time zones back and forward. Also timezone should be set in stone and not dependent on school setting in Zamenhof interface.

**What we propose**:
All dates in parameter and properties of response objects are formatted in UTC timezone.
This will be most universal and we will be able to easily adjust date/time presentation to clients timezone.

For example (this is not an exhaustive list - just illustration of the idea):

A. method for getting available classes receives „start” parameter. This currently is in student timezone - we wish to have it in UTC zone.
B. response from getting available classes contains class dates. We wish to have them in UTC timezone.

This change must be backward compatible - so probably new parameter needs to be introduced to indicate that UTC timezone is used.

**Comment by indrajitlahiri** [comment]
I have changed the date in GMT for 4 apis from Zamenhof side, they are

1. available class
2. book class
3. re-book class
4. list-book-class

Please note all I have uploaded in the development server lapdev.me ( not in production languagepanel.com) , so for now the API urls will be like the following

1. https://lapdev.me/api/v2/available-class.php
2. https://lapdev.me/api/v2/book-class.php
3. https://lapdev.me/api/v2/rebook-class.php
4. https://lapdev.me/api/v2/list-book-class.php

The way to test the available class API is possible thru the simulator like below

https://lapdev.me/api_call/v2/2.html

The non GMT previous version is also there with the v2 in the url. When the v2 version will be approved let me know, I will put this v2 (with GMT) version in the production directly.
